### ISSUE TITLE
Milestone V2 - UAT

### ISSUE THREAD

**Issue by alamparelli** [alamparelli/my-portfolio-showcase#49]
Milestone V2
OWNER

- [ ] US6: As the owner, I can add new projects from the admin interface
- [ ] US7: As the owner, I can modify already visible projects from the admin interface
- [ ] US8: As the owner, I can delete already visible projects from the admin interface

CI/CD:

- [ ]  Deployment PIPELINE: From GITHUB Actions
- [ ]  Test PIPELINE: From GITHUB Actions

_Originally posted by @alamparelli in https://github.com/alamparelli/my-portfolio-showcase/issues/21#issuecomment-2323793431_
